#!/usr/bin/env python3
"""
PNG to RGB565 Converter for ESP32 LCD sprites.

Converts PNG frames to C header files with RGB565 pixel data.
Transparent pixels (alpha < 128 or matching #1a1a2e) use key color 0x18C5.

Usage:
    python tools/png2rgb565.py input_dir output_header --name array_prefix

Example:
    python tools/png2rgb565.py sprites/idle firmware/main/idle_frames.h --name idle
"""

import argparse
import os
import re
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Install it with:")
    print("  pip install Pillow")
    sys.exit(1)

# Transparency key color in RGB565
TRANSPARENT_KEY = 0x18C5

# Background color to treat as transparent (#1a1a2e)
BG_COLOR = (0x1A, 0x1A, 0x2E)


def rgb_to_565(r, g, b):
    """Convert 8-bit RGB to RGB565."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def blend_over_bg(r, g, b, a):
    """Alpha-composite an RGBA pixel over the background color.
    Semi-transparent pixels (e.g. glows, shadows) become opaque blended colors
    instead of being discarded."""
    alpha = a / 255.0
    br = int(r * alpha + BG_COLOR[0] * (1 - alpha))
    bg = int(g * alpha + BG_COLOR[1] * (1 - alpha))
    bb = int(b * alpha + BG_COLOR[2] * (1 - alpha))
    return br, bg, bb


def convert_png_to_rgb565(image_path):
    """Convert a PNG image to a list of RGB565 values."""
    img = Image.open(image_path).convert("RGBA")
    width, height = img.size
    pixels = []

    for y in range(height):
        for x in range(width):
            r, g, b, a = img.getpixel((x, y))
            if a == 0 or (a == 255 and (r, g, b) == BG_COLOR):
                # Fully transparent or exact background match
                pixels.append(TRANSPARENT_KEY)
            elif a < 255:
                # Semi-transparent: composite over background
                cr, cg, cb = blend_over_bg(r, g, b, a)
                val = rgb_to_565(cr, cg, cb)
                if val == TRANSPARENT_KEY:
                    val = TRANSPARENT_KEY + 1
                pixels.append(val)
            else:
                val = rgb_to_565(r, g, b)
                # Avoid accidental collision with transparent key
                if val == TRANSPARENT_KEY:
                    val = TRANSPARENT_KEY + 1
                pixels.append(val)

    return pixels, width, height


def format_pixel_array(pixels, indent="    "):
    """Format pixel data as a C array."""
    lines = []
    for i in range(0, len(pixels), 16):
        chunk = pixels[i:i + 16]
        hex_vals = ", ".join(f"0x{v:04X}" for v in chunk)
        lines.append(f"{indent}{hex_vals},")
    return "\n".join(lines)


def rle_encode(pixels):
    """RLE-encode a list of pixel values into (value, count) pairs."""
    if not pixels:
        return []
    runs = []
    current_val = pixels[0]
    current_count = 1
    for pixel in pixels[1:]:
        if pixel == current_val and current_count < 65535:
            current_count += 1
        else:
            runs.append((current_val, current_count))
            current_val = pixel
            current_count = 1
    runs.append((current_val, current_count))
    return runs


def format_rle_array(runs, indent="    "):
    """Format RLE (value, count) pairs as a C array."""
    lines = []
    for i in range(0, len(runs), 8):
        chunk = runs[i:i + 8]
        pairs = ", ".join(f"0x{v:04X},{c}" for v, c in chunk)
        lines.append(f"{indent}{pairs},")
    return "\n".join(lines)


def generate_header(frames_data, prefix, width, height):
    """Generate a C header with RLE-compressed sprite data."""
    guard = f"{prefix.upper()}_FRAMES_H"
    frame_count = len(frames_data)

    # RLE-encode all frames and compute offsets
    all_rle_runs = []
    frame_offsets = []  # word offsets into packed data
    word_offset = 0
    for pixels in frames_data:
        frame_offsets.append(word_offset)
        runs = rle_encode(pixels)
        all_rle_runs.extend(runs)
        word_offset += len(runs) * 2  # 2 uint16_t words per run pair
    frame_offsets.append(word_offset)  # sentinel

    raw_size = frame_count * width * height * 2
    rle_size = word_offset * 2
    ratio = raw_size / rle_size if rle_size > 0 else 0

    lines = []
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append("/**")
    lines.append(f" * Auto-generated by png2rgb565.py (RLE compressed)")
    lines.append(f" * {frame_count} frame(s), {width}x{height} pixels")
    lines.append(f" * Raw: {raw_size:,} bytes, RLE: {rle_size:,} bytes ({ratio:.0f}x compression)")
    lines.append(f" * Transparent key: 0x{TRANSPARENT_KEY:04X}")
    lines.append(" */")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define {prefix.upper()}_WIDTH  {width}")
    lines.append(f"#define {prefix.upper()}_HEIGHT {height}")
    lines.append(f"#define {prefix.upper()}_FRAME_COUNT {frame_count}")
    lines.append(f"#define {prefix.upper()}_TRANSPARENT_KEY 0x{TRANSPARENT_KEY:04X}")
    lines.append("")

    # Frame offset table (N+1 entries)
    lines.append(f"static const uint32_t {prefix}_frame_offsets[{frame_count + 1}] = {{")
    for i in range(0, len(frame_offsets), 8):
        chunk = frame_offsets[i:i + 8]
        vals = ", ".join(str(o) for o in chunk)
        lines.append(f"    {vals},")
    lines.append("};")
    lines.append("")

    # Packed RLE data
    lines.append(f"static const uint16_t {prefix}_rle_data[] = {{")
    lines.append(format_rle_array(all_rle_runs))
    lines.append("};")
    lines.append("")
    lines.append(f"#endif // {guard}")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Convert PNG frames to RGB565 C header"
    )
    parser.add_argument("input_dir", help="Directory containing PNG frames")
    parser.add_argument("output_header", help="Output C header file path")
    parser.add_argument(
        "--name", required=True, help="Array name prefix (e.g., 'idle')"
    )
    args = parser.parse_args()

    if not re.match(r'^[a-zA-Z_][a-zA-Z0-9_]*$', args.name):
        print(f"Error: '{args.name}' is not a valid C identifier.")
        print("  Must match: ^[a-zA-Z_][a-zA-Z0-9_]*$")
        sys.exit(1)

    input_dir = Path(args.input_dir)
    if not input_dir.is_dir():
        print(f"Error: {input_dir} is not a directory")
        sys.exit(1)

    # Find PNG files sorted alphabetically
    png_files = sorted(input_dir.glob("*.png"))
    if not png_files:
        print(f"Error: No PNG files found in {input_dir}")
        sys.exit(1)

    print(f"Found {len(png_files)} PNG file(s) in {input_dir}")

    frames_data = []
    width, height = None, None

    for png_file in png_files:
        pixels, w, h = convert_png_to_rgb565(png_file)
        if width is None:
            width, height = w, h
        elif (w, h) != (width, height):
            print(f"Warning: {png_file.name} is {w}x{h}, expected {width}x{height}. Skipping.")
            continue

        frames_data.append(pixels)
        print(f"  Converted: {png_file.name} ({w}x{h}, {len(pixels)} pixels)")

    if not frames_data:
        print("Error: No valid frames converted")
        sys.exit(1)

    # Generate header
    header = generate_header(frames_data, args.name, width, height)

    # Write output
    output_path = Path(args.output_header)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header)

    print(f"\nGenerated: {output_path}")
    print(f"  Prefix: {args.name}")
    print(f"  Frames: {len(frames_data)}")
    print(f"  Size: {width}x{height}")
    print(f"  Transparent key: 0x{TRANSPARENT_KEY:04X}")


if __name__ == "__main__":
    main()
